const countries = [
  { name: "Afghanistan", dialCode: "+93", flag: "https://flagcdn.com/48x36/af.png" },
  { name: "Albania", dialCode: "+355", flag: "https://flagcdn.com/48x36/al.png" },
  { name: "Algeria", dialCode: "+213", flag: "https://flagcdn.com/48x36/dz.png" },
  { name: "Andorra", dialCode: "+376", flag: "https://flagcdn.com/48x36/ad.png" },
  { name: "Angola", dialCode: "+244", flag: "https://flagcdn.com/48x36/ao.png" },
  { name: "Antigua and Barbuda", dialCode: "+1-268", flag: "https://flagcdn.com/48x36/ag.png" },
  { name: "Argentina", dialCode: "+54", flag: "https://flagcdn.com/48x36/ar.png" },
  { name: "Armenia", dialCode: "+374", flag: "https://flagcdn.com/48x36/am.png" },
  { name: "Australia", dialCode: "+61", flag: "https://flagcdn.com/48x36/au.png" },
  { name: "Austria", dialCode: "+43", flag: "https://flagcdn.com/48x36/at.png" },
  { name: "Azerbaijan", dialCode: "+994", flag: "https://flagcdn.com/48x36/az.png" },
  { name: "Bahamas", dialCode: "+1-242", flag: "https://flagcdn.com/48x36/bs.png" },
  { name: "Bahrain", dialCode: "+973", flag: "https://flagcdn.com/48x36/bh.png" },
  { name: "Bangladesh", dialCode: "+880", flag: "https://flagcdn.com/48x36/bd.png" },
  { name: "Barbados", dialCode: "+1-246", flag: "https://flagcdn.com/48x36/bb.png" },
  { name: "Belarus", dialCode: "+375", flag: "https://flagcdn.com/48x36/by.png" },
  { name: "Belgium", dialCode: "+32", flag: "https://flagcdn.com/48x36/be.png" },
  { name: "Belize", dialCode: "+501", flag: "https://flagcdn.com/48x36/bz.png" },
  { name: "Benin", dialCode: "+229", flag: "https://flagcdn.com/48x36/bj.png" },
  { name: "Bhutan", dialCode: "+975", flag: "https://flagcdn.com/48x36/bt.png" },
  { name: "Bolivia", dialCode: "+591", flag: "https://flagcdn.com/48x36/bo.png" },
  { name: "Bosnia and Herzegovina", dialCode: "+387", flag: "https://flagcdn.com/48x36/ba.png" },
  { name: "Botswana", dialCode: "+267", flag: "https://flagcdn.com/48x36/bw.png" },
  { name: "Brazil", dialCode: "+55", flag: "https://flagcdn.com/48x36/br.png" },
  { name: "Brunei", dialCode: "+673", flag: "https://flagcdn.com/48x36/bn.png" },
  { name: "Bulgaria", dialCode: "+359", flag: "https://flagcdn.com/48x36/bg.png" },
  { name: "Burkina Faso", dialCode: "+226", flag: "https://flagcdn.com/48x36/bf.png" },
  { name: "Burundi", dialCode: "+257", flag: "https://flagcdn.com/48x36/bi.png" },
  { name: "Cabo Verde", dialCode: "+238", flag: "https://flagcdn.com/48x36/cv.png" },
  { name: "Cambodia", dialCode: "+855", flag: "https://flagcdn.com/48x36/kh.png" },
  { name: "Cameroon", dialCode: "+237", flag: "https://flagcdn.com/48x36/cm.png" },
  { name: "Canada", dialCode: "+1", flag: "https://flagcdn.com/48x36/ca.png" },
  { name: "Central African Republic", dialCode: "+236", flag: "https://flagcdn.com/48x36/cf.png" },
  { name: "Chad", dialCode: "+235", flag: "https://flagcdn.com/48x36/td.png" },
  { name: "Chile", dialCode: "+56", flag: "https://flagcdn.com/48x36/cl.png" },
  { name: "China", dialCode: "+86", flag: "https://flagcdn.com/48x36/cn.png" },
  { name: "Colombia", dialCode: "+57", flag: "https://flagcdn.com/48x36/co.png" },
  { name: "Comoros", dialCode: "+269", flag: "https://flagcdn.com/48x36/km.png" },
  { name: "Congo (Congo-Brazzaville)", dialCode: "+242", flag: "https://flagcdn.com/48x36/cg.png" },
  { name: "Costa Rica", dialCode: "+506", flag: "https://flagcdn.com/48x36/cr.png" },
  { name: "Croatia", dialCode: "+385", flag: "https://flagcdn.com/48x36/hr.png" },
  { name: "Cuba", dialCode: "+53", flag: "https://flagcdn.com/48x36/cu.png" },
  { name: "Cyprus", dialCode: "+357", flag: "https://flagcdn.com/48x36/cy.png" },
  { name: "Czechia", dialCode: "+420", flag: "https://flagcdn.com/48x36/cz.png" },
  { name: "Democratic Republic of the Congo", dialCode: "+243", flag: "https://flagcdn.com/48x36/cd.png" },
  { name: "Denmark", dialCode: "+45", flag: "https://flagcdn.com/48x36/dk.png" },
  { name: "Djibouti", dialCode: "+253", flag: "https://flagcdn.com/48x36/dj.png" },
  { name: "Dominica", dialCode: "+1-767", flag: "https://flagcdn.com/48x36/dm.png" },
  { name: "Dominican Republic", dialCode: "+1-809", flag: "https://flagcdn.com/48x36/do.png" },
  { name: "Ecuador", dialCode: "+593", flag: "https://flagcdn.com/48x36/ec.png" },
  { name: "Egypt", dialCode: "+20", flag: "https://flagcdn.com/48x36/eg.png" },
  { name: "El Salvador", dialCode: "+503", flag: "https://flagcdn.com/48x36/sv.png" },
  { name: "Equatorial Guinea", dialCode: "+240", flag: "https://flagcdn.com/48x36/gq.png" },
  { name: "Eritrea", dialCode: "+291", flag: "https://flagcdn.com/48x36/er.png" },
  { name: "Estonia", dialCode: "+372", flag: "https://flagcdn.com/48x36/ee.png" },
  { name: "Eswatini", dialCode: "+268", flag: "https://flagcdn.com/48x36/sz.png" },
  { name: "Ethiopia", dialCode: "+251", flag: "https://flagcdn.com/48x36/et.png" },
  { name: "Fiji", dialCode: "+679", flag: "https://flagcdn.com/48x36/fj.png" },
  { name: "Finland", dialCode: "+358", flag: "https://flagcdn.com/48x36/fi.png" },
  { name: "France", dialCode: "+33", flag: "https://flagcdn.com/48x36/fr.png" },
  { name: "Gabon", dialCode: "+241", flag: "https://flagcdn.com/48x36/ga.png" },
  { name: "Gambia", dialCode: "+220", flag: "https://flagcdn.com/48x36/gm.png" },
  { name: "Georgia", dialCode: "+995", flag: "https://flagcdn.com/48x36/ge.png" },
  { name: "Germany", dialCode: "+49", flag: "https://flagcdn.com/48x36/de.png" },
  { name: "Ghana", dialCode: "+233", flag: "https://flagcdn.com/48x36/gh.png" },
  { name: "Greece", dialCode: "+30", flag: "https://flagcdn.com/48x36/gr.png" },
  { name: "Grenada", dialCode: "+1-473", flag: "https://flagcdn.com/48x36/gd.png" },
  { name: "Guatemala", dialCode: "+502", flag: "https://flagcdn.com/48x36/gt.png" },
  { name: "Guinea", dialCode: "+224", flag: "https://flagcdn.com/48x36/gn.png" },
  { name: "Guinea-Bissau", dialCode: "+245", flag: "https://flagcdn.com/48x36/gw.png" },
  { name: "Guyana", dialCode: "+592", flag: "https://flagcdn.com/48x36/gy.png" },
  { name: "Haiti", dialCode: "+509", flag: "https://flagcdn.com/48x36/ht.png" },
  { name: "Holy See", dialCode: "+379", flag: "https://flagcdn.com/48x36/va.png" },
  { name: "Honduras", dialCode: "+504", flag: "https://flagcdn.com/48x36/hn.png" },
  { name: "Hungary", dialCode: "+36", flag: "https://flagcdn.com/48x36/hu.png" },
  { name: "Iceland", dialCode: "+354", flag: "https://flagcdn.com/48x36/is.png" },
  { name: "India", dialCode: "+91", flag: "https://flagcdn.com/48x36/in.png" },
  { name: "Indonesia", dialCode: "+62", flag: "https://flagcdn.com/48x36/id.png" },
  { name: "Iran", dialCode: "+98", flag: "https://flagcdn.com/48x36/ir.png" },
  { name: "Iraq", dialCode: "+964", flag: "https://flagcdn.com/48x36/iq.png" },
  { name: "Ireland", dialCode: "+353", flag: "https://flagcdn.com/48x36/ie.png" },
  { name: "Israel", dialCode: "+972", flag: "https://flagcdn.com/48x36/il.png" },
  { name: "Italy", dialCode: "+39", flag: "https://flagcdn.com/48x36/it.png" },
  { name: "Jamaica", dialCode: "+1-876", flag: "https://flagcdn.com/48x36/jm.png" },
  { name: "Japan", dialCode: "+81", flag: "https://flagcdn.com/48x36/jp.png" },
  { name: "Jordan", dialCode: "+962", flag: "https://flagcdn.com/48x36/jo.png" },
  { name: "Kazakhstan", dialCode: "+7", flag: "https://flagcdn.com/48x36/kz.png" },
  { name: "Kenya", dialCode: "+254", flag: "https://flagcdn.com/48x36/ke.png" },
  { name: "Kiribati", dialCode: "+686", flag: "https://flagcdn.com/48x36/ki.png" },
  { name: "Kuwait", dialCode: "+965", flag: "https://flagcdn.com/48x36/kw.png" },
  { name: "Kyrgyzstan", dialCode: "+996", flag: "https://flagcdn.com/48x36/kg.png" },
  { name: "Laos", dialCode: "+856", flag: "https://flagcdn.com/48x36/la.png" },
  { name: "Latvia", dialCode: "+371", flag: "https://flagcdn.com/48x36/lv.png" },
  { name: "Lebanon", dialCode: "+961", flag: "https://flagcdn.com/48x36/lb.png" },
  { name: "Lesotho", dialCode: "+266", flag: "https://flagcdn.com/48x36/ls.png" },
  { name: "Liberia", dialCode: "+231", flag: "https://flagcdn.com/48x36/lr.png" },
  { name: "Libya", dialCode: "+218", flag: "https://flagcdn.com/48x36/ly.png" },
  { name: "Liechtenstein", dialCode: "+423", flag: "https://flagcdn.com/48x36/li.png" },
  { name: "Lithuania", dialCode: "+370", flag: "https://flagcdn.com/48x36/lt.png" },
  { name: "Luxembourg", dialCode: "+352", flag: "https://flagcdn.com/48x36/lu.png" },
  { name: "Madagascar", dialCode: "+261", flag: "https://flagcdn.com/48x36/mg.png" },
  { name: "Malawi", dialCode: "+265", flag: "https://flagcdn.com/48x36/mw.png" },
  { name: "Malaysia", dialCode: "+60", flag: "https://flagcdn.com/48x36/my.png" },
  { name: "Maldives", dialCode: "+960", flag: "https://flagcdn.com/48x36/mv.png" },
  { name: "Mali", dialCode: "+223", flag: "https://flagcdn.com/48x36/ml.png" },
  { name: "Malta", dialCode: "+356", flag: "https://flagcdn.com/48x36/mt.png" },
  { name: "Marshall Islands", dialCode: "+692", flag: "https://flagcdn.com/48x36/mh.png" },
  { name: "Mauritania", dialCode: "+222", flag: "https://flagcdn.com/48x36/mr.png" },
  { name: "Mauritius", dialCode: "+230", flag: "https://flagcdn.com/48x36/mu.png" },
  { name: "Mexico", dialCode: "+52", flag: "https://flagcdn.com/48x36/mx.png" },
  { name: "Micronesia", dialCode: "+691", flag: "https://flagcdn.com/48x36/fm.png" },
  { name: "Moldova", dialCode: "+373", flag: "https://flagcdn.com/48x36/md.png" },
  { name: "Monaco", dialCode: "+377", flag: "https://flagcdn.com/48x36/mc.png" },
  { name: "Mongolia", dialCode: "+976", flag: "https://flagcdn.com/48x36/mn.png" },
  { name: "Montenegro", dialCode: "+382", flag: "https://flagcdn.com/48x36/me.png" },
  { name: "Morocco", dialCode: "+212", flag: "https://flagcdn.com/48x36/ma.png" },
  { name: "Mozambique", dialCode: "+258", flag: "https://flagcdn.com/48x36/mz.png" },
  { name: "Myanmar", dialCode: "+95", flag: "https://flagcdn.com/48x36/mm.png" },
  { name: "Namibia", dialCode: "+264", flag: "https://flagcdn.com/48x36/na.png" },
  { name: "Nauru", dialCode: "+674", flag: "https://flagcdn.com/48x36/nr.png" },
  { name: "Nepal", dialCode: "+977", flag: "https://flagcdn.com/48x36/np.png" },
  { name: "Netherlands", dialCode: "+31", flag: "https://flagcdn.com/48x36/nl.png" },
  { name: "New Zealand", dialCode: "+64", flag: "https://flagcdn.com/48x36/nz.png" },
  { name: "Nicaragua", dialCode: "+505", flag: "https://flagcdn.com/48x36/ni.png" },
  { name: "Niger", dialCode: "+227", flag: "https://flagcdn.com/48x36/ne.png" },
  { name: "Nigeria", dialCode: "+234", flag: "https://flagcdn.com/48x36/ng.png" },
  { name: "North Korea", dialCode: "+850", flag: "https://flagcdn.com/48x36/kp.png" },
  { name: "North Macedonia", dialCode: "+389", flag: "https://flagcdn.com/48x36/mk.png" },
  { name: "Norway", dialCode: "+47", flag: "https://flagcdn.com/48x36/no.png" },
  { name: "Oman", dialCode: "+968", flag: "https://flagcdn.com/48x36/om.png" },
  { name: "Pakistan", dialCode: "+92", flag: "https://flagcdn.com/48x36/pk.png" },
  { name: "Palau", dialCode: "+680", flag: "https://flagcdn.com/48x36/pw.png" },
  { name: "Palestine", dialCode: "+970", flag: "https://flagcdn.com/48x36/ps.png" },
  { name: "Panama", dialCode: "+507", flag: "https://flagcdn.com/48x36/pa.png" },
  { name: "Papua New Guinea", dialCode: "+675", flag: "https://flagcdn.com/48x36/pg.png" },
  { name: "Paraguay", dialCode: "+595", flag: "https://flagcdn.com/48x36/py.png" },
  { name: "Peru", dialCode: "+51", flag: "https://flagcdn.com/48x36/pe.png" },
  { name: "Philippines", dialCode: "+63", flag: "https://flagcdn.com/48x36/ph.png" },
  { name: "Poland", dialCode: "+48", flag: "https://flagcdn.com/48x36/pl.png" },
  { name: "Portugal", dialCode: "+351", flag: "https://flagcdn.com/48x36/pt.png" },
  { name: "Qatar", dialCode: "+974", flag: "https://flagcdn.com/48x36/qa.png" },
  { name: "Romania", dialCode: "+40", flag: "https://flagcdn.com/48x36/ro.png" },
  { name: "Russia", dialCode: "+7", flag: "https://flagcdn.com/48x36/ru.png" },
  { name: "Rwanda", dialCode: "+250", flag: "https://flagcdn.com/48x36/rw.png" },
  { name: "Saint Kitts and Nevis", dialCode: "+1-869", flag: "https://flagcdn.com/48x36/kn.png" },
  { name: "Saint Lucia", dialCode: "+1-758", flag: "https://flagcdn.com/48x36/lc.png" },
  { name: "Saint Vincent and the Grenadines", dialCode: "+1-784", flag: "https://flagcdn.com/48x36/vc.png" },
  { name: "Samoa", dialCode: "+685", flag: "https://flagcdn.com/48x36/ws.png" },
  { name: "San Marino", dialCode: "+378", flag: "https://flagcdn.com/48x36/sm.png" },
  { name: "Sao Tome and Principe", dialCode: "+239", flag: "https://flagcdn.com/48x36/st.png" },
  { name: "Saudi Arabia", dialCode: "+966", flag: "https://flagcdn.com/48x36/sa.png" },
  { name: "Senegal", dialCode: "+221", flag: "https://flagcdn.com/48x36/sn.png" },
  { name: "Serbia", dialCode: "+381", flag: "https://flagcdn.com/48x36/rs.png" },
  { name: "Seychelles", dialCode: "+248", flag: "https://flagcdn.com/48x36/sc.png" },
  { name: "Sierra Leone", dialCode: "+232", flag: "https://flagcdn.com/48x36/sl.png" },
  { name: "Singapore", dialCode: "+65", flag: "https://flagcdn.com/48x36/sg.png" },
  { name: "Slovakia", dialCode: "+421", flag: "https://flagcdn.com/48x36/sk.png" },
  { name: "Slovenia", dialCode: "+386", flag: "https://flagcdn.com/48x36/si.png" },
  { name: "Solomon Islands", dialCode: "+677", flag: "https://flagcdn.com/48x36/sb.png" },
  { name: "Somalia", dialCode: "+252", flag: "https://flagcdn.com/48x36/so.png" },
  { name: "South Africa", dialCode: "+27", flag: "https://flagcdn.com/48x36/za.png" },
  { name: "South Korea", dialCode: "+82", flag: "https://flagcdn.com/48x36/kr.png" },
  { name: "South Sudan", dialCode: "+211", flag: "https://flagcdn.com/48x36/ss.png" },
  { name: "Spain", dialCode: "+34", flag: "https://flagcdn.com/48x36/es.png" },
  { name: "Sri Lanka", dialCode: "+94", flag: "https://flagcdn.com/48x36/lk.png" },
  { name: "Sudan", dialCode: "+249", flag: "https://flagcdn.com/48x36/sd.png" },
  { name: "Suriname", dialCode: "+597", flag: "https://flagcdn.com/48x36/sr.png" },
  { name: "Sweden", dialCode: "+46", flag: "https://flagcdn.com/48x36/se.png" },
  { name: "Switzerland", dialCode: "+41", flag: "https://flagcdn.com/48x36/ch.png" },
  { name: "Syria", dialCode: "+963", flag: "https://flagcdn.com/48x36/sy.png" },
  { name: "Taiwan", dialCode: "+886", flag: "https://flagcdn.com/48x36/tw.png" },
  { name: "Tajikistan", dialCode: "+992", flag: "https://flagcdn.com/48x36/tj.png" },
  { name: "Tanzania", dialCode: "+255", flag: "https://flagcdn.com/48x36/tz.png" },
  { name: "Thailand", dialCode: "+66", flag: "https://flagcdn.com/48x36/th.png" },
  { name: "Timor-Leste", dialCode: "+670", flag: "https://flagcdn.com/48x36/tl.png" },
  { name: "Togo", dialCode: "+228", flag: "https://flagcdn.com/48x36/tg.png" },
  { name: "Tonga", dialCode: "+676", flag: "https://flagcdn.com/48x36/to.png" },
  { name: "Trinidad and Tobago", dialCode: "+1-868", flag: "https://flagcdn.com/48x36/tt.png" },
  { name: "Tunisia", dialCode: "+216", flag: "https://flagcdn.com/48x36/tn.png" },
  { name: "Turkey", dialCode: "+90", flag: "https://flagcdn.com/48x36/tr.png" },
  { name: "Turkmenistan", dialCode: "+993", flag: "https://flagcdn.com/48x36/tm.png" },
  { name: "Tuvalu", dialCode: "+688", flag: "https://flagcdn.com/48x36/tv.png" },
  { name: "Uganda", dialCode: "+256", flag: "https://flagcdn.com/48x36/ug.png" },
  { name: "Ukraine", dialCode: "+380", flag: "https://flagcdn.com/48x36/ua.png" },
  { name: "United Arab Emirates", dialCode: "+971", flag: "https://flagcdn.com/48x36/ae.png" },
  { name: "United Kingdom", dialCode: "+44", flag: "https://flagcdn.com/48x36/gb.png" },
  { name: "United States of America", dialCode: "+1", flag: "https://flagcdn.com/48x36/us.png" },
  { name: "Uruguay", dialCode: "+598", flag: "https://flagcdn.com/48x36/uy.png" },
  { name: "Uzbekistan", dialCode: "+998", flag: "https://flagcdn.com/48x36/uz.png" },
  { name: "Vanuatu", dialCode: "+678", flag: "https://flagcdn.com/48x36/vu.png" },
  { name: "Venezuela", dialCode: "+58", flag: "https://flagcdn.com/48x36/ve.png" },
  { name: "Vietnam", dialCode: "+84", flag: "https://flagcdn.com/48x36/vn.png" },
  { name: "Yemen", dialCode: "+967", flag: "https://flagcdn.com/48x36/ye.png" },
  { name: "Zambia", dialCode: "+260", flag: "https://flagcdn.com/48x36/zm.png" },
  { name: "Zimbabwe", dialCode: "+263", flag: "https://flagcdn.com/48x36/zw.png" }
];

export default countries;